from django.core.files import File
from django.core.serializers import json
from django.http import HttpResponse, JsonResponse
from ..models import Inspections, CompressedGasCylinder, AccidentInvestigationRCAForm, AWPForm, ConfinedSpaceAuthorization, ConfinedSpaceEntry, DailyExcavation, DailyMaintenance, EarthmovingEquipment
from datetime import date
import os
import os.path
import time
from pathlib import Path
from django.conf import settings
from django.apps import apps


def accident_investigation_rca_form(request):
    draft = AccidentInvestigationRCAForm()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.job_title = request.POST.get('job_title', None)
    draft.address = request.POST.get('address', None)
    draft.date_occurrence = request.POST.get('date_occurrence', None)
    draft.lcoation = request.POST.get('lcoation', None)
    draft.date_reported = request.POST.get('date_reported', None)
    draft.to_whom = request.POST.get('to_whom', None)
    draft.incident = request.POST.getlist('incident', None)
    draft.des_happened = request.POST.get('des_happened', None)
    draft.des_nature = request.POST.get('des_nature', None)
    draft.body_injured = request.POST.getlist('body_injured', None)
    draft.type_accident = request.POST.getlist('type_accident', None)
    draft.wit_name_one = request.POST.get('wit_name_one', None)
    draft.wit_ph_one = request.POST.get('wit_ph_one', None)
    draft.wit_addr_one = request.POST.get('wit_addr_one', None)
    draft.wit_ph_two = request.POST.get('wit_ph_two', None)
    draft.wit_name_two = request.POST.get('wit_name_two', None)
    draft.wit_ph_three = request.POST.get('wit_ph_three', None)
    draft.wit_addr_two = request.POST.get('wit_addr_two', None)
    draft.wit_ph_four = request.POST.get('wit_ph_four', None)
    draft.wit_name_three = request.POST.get('wit_name_three', None)
    draft.wit_ph_five = request.POST.get('wit_ph_five', None)
    draft.wit_addr_three = request.POST.get('wit_addr_three', None)
    draft.wit_ph_six = request.POST.get('wit_ph_six', None)
    draft.phy_name = request.POST.get('phy_name', None)
    draft.phy_ph_one = request.POST.get('phy_ph_one', None)
    draft.phy_addr = request.POST.get('phy_addr', None)
    draft.phy_ph_two = request.POST.get('phy_ph_two', None)
    draft.causes = request.POST.getlist('causes', None)
    draft.des_exist = request.POST.get('des_exist', None)
    draft.corr_actions = request.POST.getlist('corr_actions', None)
    draft.des_action = request.POST.get('des_action', None)
    draft.invest_name = request.POST.get('invest_name', None)
    draft.invest_sign = request.POST.get('invest_sign', None)
    draft.invest_date = request.POST.get('invest_date', None)
    draft.review_name = request.POST.get('review_name', None)
    draft.review_sign = request.POST.get('review_sign', None)
    draft.review_date = request.POST.get('review_date', None)
    draft.review_first_name = request.POST.get('review_first_name', None)
    draft.review_job_title = request.POST.get('review_job_title', None)
    draft.review_addr = request.POST.get('review_addr', None)
    draft.review_date_occurrence = request.POST.get('review_date_occurrence', None)
    draft.review_location = request.POST.get('review_location', None)
    draft.review_date_report = request.POST.get('review_date_report', None)
    draft.review_to_whom = request.POST.get('review_to_whom', None)
    draft.illness = request.POST.getlist('illness', None)
    draft.des_injury = request.POST.get('des_injury', None)
    draft.des_materials = request.POST.get('des_materials', None)
    draft.body_injured_second = request.POST.getlist('body_injured_second', None)
    draft.type_incident = request.POST.getlist('type_incident', None)
    draft.wit_two_name_one = request.POST.get('wit_two_name_one', None)
    draft.wit_two_ph_one = request.POST.get('wit_two_ph_one', None)
    draft.wit_two_addr_one = request.POST.get('wit_two_addr_one', None)
    draft.wit_two_ph_two = request.POST.get('wit_two_ph_two', None)
    draft.wit_two_name_two = request.POST.get('wit_two_name_two', None)
    draft.wit_two_ph_three = request.POST.get('wit_two_ph_three', None)
    draft.wit_two_addr_two = request.POST.get('wit_two_addr_two', None)
    draft.wit_two_ph_four = request.POST.get('wit_two_ph_four', None)
    draft.wit_two_name_three = request.POST.get('wit_two_name_three', None)
    draft.wit_two_ph_five = request.POST.get('wit_two_ph_five', None)
    draft.wit_two_addr_three = request.POST.get('wit_two_addr_three', None)
    draft.wit_two_ph_six = request.POST.get('wit_two_ph_six', None)
    draft.wit_two_emp_sign = request.POST.get('wit_two_emp_sign', None)
    draft.wit_two_date = request.POST.get('wit_two_date', None)
    draft.wit_two_supervisor = request.POST.get('wit_two_supervisor', None)
    draft.wit_two_supervisor_sign = request.POST.get('wit_two_supervisor_sign', None)
    draft.wit_two_name_four = request.POST.get('wit_two_name_four', None)
    draft.wit_two_job_title = request.POST.get('wit_two_job_title', None)
    draft.wit_two_addr_four = request.POST.get('wit_two_addr_four', None)
    draft.wit_two_date_occurance = request.POST.get('wit_two_date_occurance', None)
    draft.wit_two_location = request.POST.get('wit_two_location', None)
    draft.wit_two_wit_name = request.POST.get('wit_two_wit_name', None)
    draft.wit_two_wit_job = request.POST.get('wit_two_wit_job', None)
    draft.wit_two_wit_addr = request.POST.get('wit_two_wit_addr', None)
    draft.wit_two_loc_accident = request.POST.get('wit_two_loc_accident', None)
    draft.wit_two_date_occ = request.POST.get('wit_two_date_occ', None)
    draft.wit_two_time_occ = request.POST.get('wit_two_time_occ', None)
    draft.des_incident = request.POST.get('des_incident', None)
    draft.body_injured_third = request.POST.getlist('body_injured_third', None)
    draft.type_occupation = request.POST.getlist('type_occupation', None)
    draft.wit_sign = request.POST.get('wit_sign', None)
    draft.date = request.POST.get('date', None)
    draft.supervisor_name = request.POST.get('supervisor_name', None)
    draft.supervisor_sign = request.POST.get('supervisor_sign', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


def awp_form(request):
    draft = AWPForm()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.date = request.POST.get('date', None)
    draft.device_id = request.POST.get('device_id', None)
    draft.unit_type = request.POST.getlist('unit_type', None)
    draft.location = request.POST.get('location', None)
    draft.brakes = request.POST.get('brakes', None)
    draft.controls = request.POST.get('controls', None)
    draft.emergency = request.POST.get('emergency', None)
    draft.lower = request.POST.get('lower', None)
    draft.both_controls = request.POST.get('both_controls', None)
    draft.defective = request.POST.get('defective', None)
    draft.hydraulic = request.POST.get('hydraulic', None)
    draft.handrails = request.POST.get('handrails', None)
    draft.basket = request.POST.get('basket', None)
    draft.exhaust = request.POST.get('exhaust', None)
    draft.outriggers = request.POST.get('outriggers', None)
    draft.tires = request.POST.get('tires', None)
    draft.landings = request.POST.get('landings', None)
    draft.coolant = request.POST.get('coolant', None)
    draft.charged = request.POST.get('charged', None)
    draft.alarms = request.POST.get('alarms', None)
    draft.Drive = request.POST.get('Drive', None)
    draft.legible = request.POST.get('legible', None)
    draft.switches = request.POST.get('switches', None)
    draft.Operators = request.POST.get('Operators', None)
    draft.first_name = request.POST.get('first_name', None)
    draft.supervisor_name = request.POST.get('supervisor_name', None)
    draft.printed_name = request.POST.get('printed_name', None)
    draft.operat_name = request.POST.get('operat_name', None)
    draft.emp_by = request.POST.get('emp_by', None)
    draft.AWP = request.POST.get('AWP', None)
    draft.comments = request.POST.get('comments', None)
    draft.representative_name = request.POST.get('representative_name', None)
    draft.emp_sign = request.POST.get('emp_sign', None)
    draft.emp_date = request.POST.get('emp_date', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('Hello')


def compressed_gas_cylinder(request):
    draft = CompressedGasCylinder()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.cylinder_colour = request.POST.get('cylinder_colour', None)
    draft.cylinder_correct = request.POST.get('cylinder_correct', None)
    draft.cylinder_hoses = request.POST.get('cylinder_hoses', None)
    draft.cylinder_upright = request.POST.get('cylinder_upright', None)
    draft.cylinder_suitable = request.POST.get('cylinder_suitable', None)
    draft.cylinder_securing = request.POST.get('cylinder_securing', None)
    draft.cylinder_lifting = request.POST.get('cylinder_lifting', None)
    draft.plants_name = request.POST.get('plants_name', None)
    draft.cylinder_appropriate = request.POST.get('cylinder_appropriate', None)
    draft.cylinder_caps = request.POST.get('cylinder_caps', None)
    draft.cylinder_trolley = request.POST.get('cylinder_trolley', None)
    draft.cylinder_restrictions = request.POST.get('cylinder_restrictions', None)
    draft.cylinder_PPE = request.POST.get('cylinder_PPE', None)
    draft.cylinder_fire = request.POST.get('cylinder_fire', None)
    draft.cylinder_emergency = request.POST.get('cylinder_emergency', None)
    draft.date = request.POST.get('date', None)
    draft.cylinder_id = request.POST.get('cylinder_id', None)
    draft.isnp_name = request.POST.get('isnp_name', None)
    draft.sign = request.POST.get('sign', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


def confined_space_authorization(request):
    draft = ConfinedSpaceAuthorization();
    draft.plants_name = request.POST.get('plants_name', None)
    draft.area = request.POST.get('area', None)
    draft.date_issue = request.POST.get('date_issue', None)
    draft.start_time = request.POST.get('start_time', None)
    draft.expiry_time = request.POST.get('expiry_time', None)
    draft.mastercard = request.POST.get('mastercard', None)
    draft.equipment_id = request.POST.get('equipment_id', None)
    draft.equipment_name = request.POST.get('equipment_name', None)
    draft.des_hazardous = request.POST.get('des_hazardous', None)
    draft.equip_hazrdous = request.POST.get('equip_hazrdous', None)
    draft.remove_hazrdous = request.POST.get('remove_hazrdous', None)
    draft.LEL = request.POST.get('LEL', None)
    draft.oxygen = request.POST.get('oxygen', None)
    draft.H2S = request.POST.get('H2S', None)
    draft.CO = request.POST.get('CO', None)
    draft.time_test_one = request.POST.get('time_test_one', None)
    draft.person_conducting_test = request.POST.get('person_conducting_test', None)
    draft.print_one = request.POST.get('print_one', None)
    draft.sign_one = request.POST.get('sign_one', None)
    draft.hazardous_reading = request.POST.get('hazardous_reading', None)
    draft.time_test_two = request.POST.get('time_test_two', None)
    draft.print_two = request.POST.get('print_two', None)
    draft.print_three = request.POST.get('print_three', None)
    draft.atmos = request.POST.get('atmos', None)
    draft.atmos_other = request.POST.get('atmos_other', None)
    draft.detail_freq = request.POST.get('detail_freq', None)
    draft.protection = request.POST.get('protection', None)
    draft.protection_detail = request.POST.get('protection_detail', None)
    draft.harness = request.POST.get('harness', None)
    draft.harness_detail = request.POST.get('harness_detail', None)
    draft.goggles = request.POST.get('goggles', None)
    draft.goggles_detail = request.POST.get('goggles_detail', None)
    draft.clothing = request.POST.get('clothing', None)
    draft.clothing_detail = request.POST.get('clothing_detail', None)
    draft.other = request.POST.get('other', None)
    draft.other_detail = request.POST.get('other_detail', None)
    draft.purifying = request.POST.get('purifying', None)
    draft.purifying_detail = request.POST.get('purifying_detail', None)
    draft.breathing = request.POST.get('breathing', None)
    draft.breathing_detail = request.POST.get('breathing_detail', None)
    draft.developed = request.POST.get('developed', None)
    draft.developed_detail = request.POST.get('developed_detail', None)
    draft.intrinsically = request.POST.get('intrinsically', None)
    draft.intrinsically_detail = request.POST.get('intrinsically_detail', None)
    draft.lighting = request.POST.get('lighting', None)
    draft.lighting_detail = request.POST.get('lighting_detail', None)
    draft.place = request.POST.get('place', None)
    draft.place_detail = request.POST.get('place_detail', None)
    draft.isolation = request.POST.get('isolation', None)
    draft.isolation_detail = request.POST.get('isolation_detail', None)
    draft.blinding = request.POST.get('blinding', None)
    draft.blinding_detail = request.POST.get('blinding_detail', None)
    draft.agitators = request.POST.get('agitators', None)
    draft.agitators_detail = request.POST.get('agitators_detail', None)
    draft.portable = request.POST.get('portable', None)
    draft.portable_detail = request.POST.get('portable_detail', None)
    draft.temperature = request.POST.get('temperature', None)
    draft.temperature_detail = request.POST.get('temperature_detail', None)
    draft.entry = request.POST.get('entry', None)
    draft.entry_detail = request.POST.get('entry_detail', None)
    draft.personnel = request.POST.get('personnel', None)
    draft.personnel_detail = request.POST.get('personnel_detail', None)
    draft.communication = request.POST.get('communication', None)
    draft.des_instruction = request.POST.get('des_instruction', None)
    draft.CSE_issuer_name = request.POST.get('CSE_issuer_name', None)
    draft.CSE_issuer_sign = request.POST.get('CSE_issuer_sign', None)
    draft.CSW_name = request.POST.get('CSW_name', None)
    draft.CSW_sign = request.POST.get('CSW_sign', None)
    draft.CSE_receiver_name = request.POST.get('CSE_receiver_name', None)
    draft.CSE_receiver_sign = request.POST.get('CSE_receiver_sign', None)
    draft.main_auth_name = request.POST.get('main_auth_name', None)
    draft.main_auth_sign = request.POST.get('main_auth_sign', None)
    draft.ABSP_auth_name = request.POST.get('ABSP_auth_name', None)
    draft.ABSP_auth_sign = request.POST.get('ABSP_auth_sign', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


def confined_space_entry(request):
    draft = ConfinedSpaceEntry()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.entry_location_one = request.POST.get('entry_location_one', None)
    draft.confined_name_one = request.POST.get('confined_name_one', None)
    draft.initials_one = request.POST.get('initials_one', None)
    draft.time_in_one = request.POST.get('time_in_one', None)
    draft.time_out_one = request.POST.get('time_out_one', None)
    draft.entry_location_two = request.POST.get('entry_location_two', None)
    draft.confined_name_two = request.POST.get('confined_name_two', None)
    draft.initials_two = request.POST.get('initials_two', None)
    draft.time_in_two = request.POST.get('time_in_two', None)
    draft.time_out_two = request.POST.get('time_out_two', None)
    draft.entry_location_three = request.POST.get('entry_location_three', None)
    draft.confined_name_three = request.POST.get('confined_name_three', None)
    draft.initials_three = request.POST.get('initials_three', None)
    draft.time_in_three = request.POST.get('time_in_three', None)
    draft.time_out_three = request.POST.get('time_out_three', None)
    draft.entry_location_four = request.POST.get('entry_location_four', None)
    draft.confined_name_four = request.POST.get('confined_name_four', None)
    draft.initials_four = request.POST.get('initials_four', None)
    draft.time_in_four = request.POST.get('time_in_four', None)
    draft.time_out_four = request.POST.get('time_out_four', None)
    draft.entry_location_five = request.POST.get('entry_location_five', None)
    draft.confined_name_five = request.POST.get('confined_name_five', None)
    draft.initials_five = request.POST.get('initials_five', None)
    draft.time_in_five = request.POST.get('time_in_five', None)
    draft.time_out_five = request.POST.get('time_out_five', None)
    draft.entry_location_six = request.POST.get('entry_location_six', None)
    draft.confined_name_six = request.POST.get('confined_name_six', None)
    draft.initials_six = request.POST.get('initials_six', None)
    draft.time_in_six = request.POST.get('time_in_six', None)
    draft.time_out_six = request.POST.get('time_out_six', None)
    draft.entry_location_seven = request.POST.get('entry_location_seven', None)
    draft.confined_name_seven = request.POST.get('confined_name_seven', None)
    draft.initials_seven = request.POST.get('initials_seven', None)
    draft.time_in_seven = request.POST.get('time_in_seven', None)
    draft.time_out_seven = request.POST.get('time_out_seven', None)
    draft.entry_location_eight = request.POST.get('entry_location_eight', None)
    draft.confined_name_eight = request.POST.get('confined_name_eight', None)
    draft.initials_eight = request.POST.get('initials_eight', None)
    draft.time_in_eight = request.POST.get('time_in_eight', None)
    draft.time_out_eight = request.POST.get('time_out_eight', None)
    draft.entry_location_nine = request.POST.get('entry_location_nine', None)
    draft.confined_name_nine = request.POST.get('confined_name_nine', None)
    draft.initials_nine = request.POST.get('initials_nine', None)
    draft.time_in_nine = request.POST.get('time_in_nine', None)
    draft.time_out_nine = request.POST.get('time_out_nine', None)
    draft.entry_location_ten = request.POST.get('entry_location_ten', None)
    draft.confined_name_ten = request.POST.get('confined_name_ten', None)
    draft.initials_ten = request.POST.get('initials_ten', None)
    draft.time_in_ten = request.POST.get('time_in_ten', None)
    draft.time_out_ten = request.POST.get('time_out_ten', None)
    draft.entry_location_eleven = request.POST.get('entry_location_eleven', None)
    draft.confined_name_eleven = request.POST.get('confined_name_eleven', None)
    draft.initials_eleven = request.POST.get('initials_eleven', None)
    draft.time_in_eleven = request.POST.get('time_in_eleven', None)
    draft.time_out_eleven = request.POST.get('time_out_eleven', None)
    draft.des_comment = request.POST.get('des_comment', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


def daily_excavation(request):
    draft = DailyExcavation()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.date = request.POST.get('date', None)
    draft.area = request.POST.get('area', None)
    draft.location = request.POST.get('location', None)
    draft.weather = request.POST.get('weather', None)
    draft.rainfall = request.POST.get('rainfall', None)
    draft.authorized = request.POST.get('authorized', None)
    draft.additional_info = request.POST.get('additional_info', None)
    draft.spoil = request.POST.get('spoil', None)
    draft.tension = request.POST.get('tension', None)
    draft.trench = request.POST.get('trench', None)
    draft.seepage = request.POST.get('seepage', None)
    draft.bracing = request.POST.get('bracing', None)
    draft.caving = request.POST.get('caving', None)
    draft.zones = request.POST.get('zones', None)
    draft.egress = request.POST.get('egress', None)
    draft.certified = request.POST.get('certified', None)
    draft.shoring = request.POST.get('shoring', None)
    draft.correct = request.POST.get('correct', None)
    draft.hydraulic = request.POST.get('hydraulic', None)
    draft.adequate = request.POST.get('adequate', None)
    draft.barricades = request.POST.get('barricades', None)
    draft.boulders = request.POST.get('boulders', None)
    draft.vibrations = request.POST.get('vibrations', None)
    draft.safety = request.POST.get('safety', None)
    draft.space = request.POST.get('space', None)
    draft.supervisor_name = request.POST.get('supervisor_name', None)
    draft.sign = request.POST.get('sign', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


def daily_maintenance(request):
    draft = DailyMaintenance()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.engine_condition = request.POST.get('engine_condition', None)
    draft.engine_notes = request.POST.get('engine_notes', None)
    draft.battery_condition = request.POST.get('battery_condition', None)
    draft.battery_notes = request.POST.get('battery_notes', None)
    draft.belts_condition = request.POST.get('belts_condition', None)
    draft.belts_notes = request.POST.get('belts_notes', None)
    draft.bolts_condition = request.POST.get('bolts_condition', None)
    draft.bolts_notes = request.POST.get('bolts_notes', None)
    draft.coolant_condition = request.POST.get('coolant_condition', None)
    draft.coolant_notes = request.POST.get('coolant_notes', None)
    draft.cleaner_condition = request.POST.get('cleaner_condition', None)
    draft.cleaner_notes = request.POST.get('cleaner_notes', None)
    draft.drain_condition = request.POST.get('drain_condition', None)
    draft.drain_notes = request.POST.get('drain_notes', None)
    draft.evidence_condition = request.POST.get('evidence_condition', None)
    draft.evidence_notes = request.POST.get('evidence_notes', None)
    draft.walkways_condition = request.POST.get('walkways_condition', None)
    draft.walkways_notes = request.POST.get('walkways_notes', None)
    draft.oil_pressure_condition = request.POST.get('oil_pressure_condition', None)
    draft.oil_pressure_notes = request.POST.get('oil_pressure_notes', None)
    draft.oil_level_condition = request.POST.get('oil_level_condition', None)
    draft.oil_level_notes = request.POST.get('oil_level_notes', None)
    draft.temp_condition = request.POST.get('temp_condition', None)
    draft.temp_notes = request.POST.get('temp_notes', None)
    draft.air_cleaner_condition = request.POST.get('air_cleaner_condition', None)
    draft.air_cleaner_notes = request.POST.get('air_cleaner_notes', None)
    draft.hydraulic_condition = request.POST.get('hydraulic_condition', None)
    draft.hydraulic_notes = request.POST.get('hydraulic_notes', None)
    draft.hoses_condition = request.POST.get('hoses_condition', None)
    draft.hoses_notes = request.POST.get('hoses_notes', None)
    draft.reservoir_condition = request.POST.get('reservoir_condition', None)
    draft.reservoir_notes = request.POST.get('reservoir_notes', None)
    draft.seals_condition = request.POST.get('seals_condition', None)
    draft.seals_notes = request.POST.get('seals_notes', None)
    draft.filter_condition = request.POST.get('filter_condition', None)
    draft.filter_notes = request.POST.get('filter_notes', None)
    draft.cuts_condition = request.POST.get('cuts_condition', None)
    draft.cuts_notes = request.POST.get('cuts_notes', None)
    draft.light_condition = request.POST.get('light_condition', None)
    draft.light_notes = request.POST.get('light_notes', None)
    draft.tracks_condition = request.POST.get('tracks_condition', None)
    draft.tracks_notes = request.POST.get('tracks_notes', None)
    draft.fasteners_condition = request.POST.get('fasteners_condition', None)
    draft.fasteners_notes = request.POST.get('fasteners_notes', None)
    draft.pins_condition = request.POST.get('pins_condition', None)
    draft.pins_notes = request.POST.get('pins_notes', None)
    draft.guards_condition = request.POST.get('guards_condition', None)
    draft.guards_notes = request.POST.get('guards_notes', None)
    draft.braking_condition = request.POST.get('braking_condition', None)
    draft.braking_notes = request.POST.get('braking_notes', None)
    draft.emergency_condition = request.POST.get('emergency_condition', None)
    draft.emergency_notes = request.POST.get('emergency_notes', None)
    draft.steering_condition = request.POST.get('steering_condition', None)
    draft.steering_notes = request.POST.get('steering_notes', None)
    draft.crawler_condition = request.POST.get('crawler_condition', None)
    draft.crawler_notes = request.POST.get('crawler_notes', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


def earth_moving_equipment(request):
    draft = EarthmovingEquipment()
    draft.plants_name = request.POST.get('plants_name', None)
    draft.equipment_name = request.POST.get('equipment_name', None)
    draft.equipment = request.POST.get('equipment', None)
    draft.other_specify = request.POST.get('other_specify', None)
    draft.equipment_id = request.POST.get('equipment_id', None)
    draft.access_good = request.POST.get('access_good', None)
    draft.access_rejected = request.POST.get('access_rejected', None)
    draft.access_na = request.POST.get('access_na', None)
    draft.access_remarks = request.POST.get('access_remarks', None)
    draft.backup_good = request.POST.get('backup_good', None)
    draft.engine_condition = request.POST.get('engine_condition', None)
    draft.inspection_id = request.POST.get('inspection_id', None)
    draft.save()
    return HttpResponse('HELLO')


functions = {'compressed_gas_cylinder': compressed_gas_cylinder, 'accident_investigation_rca_form': accident_investigation_rca_form, 'awp_form': awp_form}


def insert_draft_form(request):
    aaa = 'awp_form'
    functions[aaa](request)
    return HttpResponse(aaa)
