# Generated by Django 3.1 on 2020-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'isnp_facility',
            },
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('stakeholders', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('operating_area', models.CharField(max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('datetime', models.DateField(blank=True, max_length=50)),
                ('draft_directory', models.CharField(blank=True, max_length=100)),
                ('draft_name', models.CharField(blank=True, max_length=100)),
                ('draft_slug', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(null=True)),
                ('approve', models.CharField(blank=True, max_length=100)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'isnp_inspection',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('type_slug', models.CharField(blank=True, max_length=200)),
                ('draft_html', models.TextField()),
            ],
            options={
                'db_table': 'isnp_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=100)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('role_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('user_directory', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'insp_user',
            },
        ),
    ]
