# Generated by Django 3.1 on 2020-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0003_compressedgascylinder_drafttables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='inspection_id',
            field=models.IntegerField(),
        ),
    ]
