# Generated by Django 3.1 on 2020-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0004_auto_20201003_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_PPE',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_appropriate',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_caps',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_colour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_correct',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_emergency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_fire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_hoses',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_lifting',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_restrictions',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_securing',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_suitable',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_trolley',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='cylinder_upright',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
