# Generated by Django 3.1 on 2020-10-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0005_auto_20201003_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='inspection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections'),
        ),
    ]
