# Generated by Django 3.1 on 2020-10-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0007_auto_20201003_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='inspection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insp.inspections'),
        ),
    ]
