# Generated by Django 3.1 on 2020-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0009_auto_20201005_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedgascylinder',
            name='inspection',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
