# Generated by Django 3.1 on 2020-10-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0011_auto_20201005_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drafttables',
            old_name='table_name',
            new_name='draft_func_name',
        ),
    ]
