# Generated by Django 3.1 on 2020-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0013_accidentinvestigationrcaform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='body_injured',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='body_injured_second',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='body_injured_third',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='causes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='corr_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='date_occurrence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='date_reported',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_exist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_happened',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_incident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_injury',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_materials',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='des_nature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='incident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='invest_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='invest_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='invest_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='lcoation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='phy_addr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='phy_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='phy_ph_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='phy_ph_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='plants_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_addr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_date_occurrence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_date_report',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_job_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='review_to_whom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='supervisor_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='supervisor_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='to_whom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='type_accident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='type_incident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='type_occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_addr_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_addr_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_addr_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_name_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_name_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_name_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_ph_five',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_ph_four',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_ph_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_ph_six',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_ph_three',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_ph_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_sign',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_addr_four',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_addr_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_addr_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_addr_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_date_occ',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_date_occurance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_emp_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_job_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_loc_accident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_name_four',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_name_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_name_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_name_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_ph_five',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_ph_four',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_ph_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_ph_six',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_ph_three',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_ph_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_supervisor_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_time_occ',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_wit_addr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_wit_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentinvestigationrcaform',
            name='wit_two_wit_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
