# Generated by Django 3.1 on 2020-10-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0014_auto_20201006_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWPForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plants_name', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('brakes', models.CharField(blank=True, max_length=5)),
                ('controls', models.CharField(blank=True, max_length=5)),
                ('emergency', models.CharField(blank=True, max_length=5)),
                ('lower', models.CharField(blank=True, max_length=5)),
                ('both_controls', models.CharField(blank=True, max_length=5)),
                ('defective', models.CharField(blank=True, max_length=5)),
                ('hydraulic', models.CharField(blank=True, max_length=5)),
                ('handrails', models.CharField(blank=True, max_length=5)),
                ('basket', models.CharField(blank=True, max_length=5)),
                ('exhaust', models.CharField(blank=True, max_length=5)),
                ('outriggers', models.CharField(blank=True, max_length=5)),
                ('tires', models.CharField(blank=True, max_length=5)),
                ('landings', models.CharField(blank=True, max_length=5)),
                ('coolant', models.CharField(blank=True, max_length=5)),
                ('charged', models.CharField(blank=True, max_length=5)),
                ('alarms', models.CharField(blank=True, max_length=5)),
                ('Drive', models.CharField(blank=True, max_length=5)),
                ('legible', models.CharField(blank=True, max_length=5)),
                ('switches', models.CharField(blank=True, max_length=5)),
                ('Operators', models.CharField(blank=True, max_length=5)),
                ('first_name', models.CharField(blank=True, max_length=5)),
                ('supervisor_name', models.CharField(blank=True, max_length=50)),
                ('printed_name', models.CharField(blank=True, max_length=50)),
                ('operat_name', models.CharField(blank=True, max_length=50)),
                ('emp_by', models.CharField(blank=True, max_length=50)),
                ('AWP', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('representative_name', models.CharField(blank=True, max_length=50)),
                ('emp_sign', models.CharField(blank=True, max_length=50)),
                ('emp_date', models.CharField(blank=True, max_length=50)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections')),
            ],
            options={
                'db_table': 'insp_AWPForm',
            },
        ),
    ]
