# Generated by Django 3.1 on 2020-10-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0017_confinedspaceauthorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confinedspaceauthorization',
            name='inspection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections'),
        ),
    ]
