# Generated by Django 3.1 on 2020-10-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0018_auto_20201006_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confinedspaceauthorization',
            old_name='inspection_id',
            new_name='inspection',
        ),
    ]
