# Generated by Django 3.1 on 2020-10-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0019_auto_20201006_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfinedSpaceEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plants_name', models.TextField(blank=True, null=True)),
                ('entry_location_one', models.TextField(blank=True, null=True)),
                ('confined_name_one', models.TextField(blank=True, null=True)),
                ('initials_one', models.TextField(blank=True, null=True)),
                ('time_in_one', models.TextField(blank=True, null=True)),
                ('time_out_one', models.TextField(blank=True, null=True)),
                ('entry_location_two', models.TextField(blank=True, null=True)),
                ('confined_name_two', models.TextField(blank=True, null=True)),
                ('initials_two', models.TextField(blank=True, null=True)),
                ('time_in_two', models.TextField(blank=True, null=True)),
                ('time_out_two', models.TextField(blank=True, null=True)),
                ('entry_location_three', models.TextField(blank=True, null=True)),
                ('confined_name_three', models.TextField(blank=True, null=True)),
                ('initials_three', models.TextField(blank=True, null=True)),
                ('time_in_three', models.TextField(blank=True, null=True)),
                ('time_out_three', models.TextField(blank=True, null=True)),
                ('entry_location_four', models.TextField(blank=True, null=True)),
                ('confined_name_four', models.TextField(blank=True, null=True)),
                ('initials_four', models.TextField(blank=True, null=True)),
                ('time_in_four', models.TextField(blank=True, null=True)),
                ('time_out_four', models.TextField(blank=True, null=True)),
                ('entry_location_five', models.TextField(blank=True, null=True)),
                ('confined_name_five', models.TextField(blank=True, null=True)),
                ('initials_five', models.TextField(blank=True, null=True)),
                ('time_in_five', models.TextField(blank=True, null=True)),
                ('time_out_five', models.TextField(blank=True, null=True)),
                ('entry_location_six', models.TextField(blank=True, null=True)),
                ('confined_name_six', models.TextField(blank=True, null=True)),
                ('initials_six', models.TextField(blank=True, null=True)),
                ('time_in_six', models.TextField(blank=True, null=True)),
                ('time_out_six', models.TextField(blank=True, null=True)),
                ('entry_location_seven', models.TextField(blank=True, null=True)),
                ('confined_name_seven', models.TextField(blank=True, null=True)),
                ('initials_seven', models.TextField(blank=True, null=True)),
                ('time_in_seven', models.TextField(blank=True, null=True)),
                ('time_out_seven', models.TextField(blank=True, null=True)),
                ('entry_location_eight', models.TextField(blank=True, null=True)),
                ('confined_name_eight', models.TextField(blank=True, null=True)),
                ('initials_eight', models.TextField(blank=True, null=True)),
                ('time_in_eight', models.TextField(blank=True, null=True)),
                ('time_out_eight', models.TextField(blank=True, null=True)),
                ('entry_location_nine', models.TextField(blank=True, null=True)),
                ('confined_name_nine', models.TextField(blank=True, null=True)),
                ('initials_nine', models.TextField(blank=True, null=True)),
                ('time_in_nine', models.TextField(blank=True, null=True)),
                ('time_out_nine', models.TextField(blank=True, null=True)),
                ('entry_location_ten', models.TextField(blank=True, null=True)),
                ('confined_name_ten', models.TextField(blank=True, null=True)),
                ('initials_ten', models.TextField(blank=True, null=True)),
                ('time_in_ten', models.TextField(blank=True, null=True)),
                ('time_out_ten', models.TextField(blank=True, null=True)),
                ('entry_location_eleven', models.TextField(blank=True, null=True)),
                ('confined_name_eleven', models.TextField(blank=True, null=True)),
                ('initials_eleven', models.TextField(blank=True, null=True)),
                ('time_in_eleven', models.TextField(blank=True, null=True)),
                ('time_out_eleven', models.TextField(blank=True, null=True)),
                ('des_comment', models.TextField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections')),
            ],
            options={
                'db_table': 'insp_ConfinedSpaceEntry',
            },
        ),
    ]
