# Generated by Django 3.1 on 2020-10-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0022_auto_20201006_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plants_name', models.TextField(blank=True, null=True)),
                ('engine_condition', models.TextField(blank=True, null=True)),
                ('engine_notes', models.TextField(blank=True, null=True)),
                ('battery_condition', models.TextField(blank=True, null=True)),
                ('battery_notes', models.TextField(blank=True, null=True)),
                ('belts_condition', models.TextField(blank=True, null=True)),
                ('belts_notes', models.TextField(blank=True, null=True)),
                ('bolts_condition', models.TextField(blank=True, null=True)),
                ('bolts_notes', models.TextField(blank=True, null=True)),
                ('coolant_condition', models.TextField(blank=True, null=True)),
                ('coolant_notes', models.TextField(blank=True, null=True)),
                ('cleaner_condition', models.TextField(blank=True, null=True)),
                ('cleaner_notes', models.TextField(blank=True, null=True)),
                ('drain_condition', models.TextField(blank=True, null=True)),
                ('drain_notes', models.TextField(blank=True, null=True)),
                ('evidence_condition', models.TextField(blank=True, null=True)),
                ('evidence_notes', models.TextField(blank=True, null=True)),
                ('walkways_condition', models.TextField(blank=True, null=True)),
                ('walkways_notes', models.TextField(blank=True, null=True)),
                ('oil_pressure_condition', models.TextField(blank=True, null=True)),
                ('oil_pressure_notes', models.TextField(blank=True, null=True)),
                ('oil_level_condition', models.TextField(blank=True, null=True)),
                ('oil_level_notes', models.TextField(blank=True, null=True)),
                ('temp_condition', models.TextField(blank=True, null=True)),
                ('temp_notes', models.TextField(blank=True, null=True)),
                ('air_cleaner_condition', models.TextField(blank=True, null=True)),
                ('air_cleaner_notes', models.TextField(blank=True, null=True)),
                ('hydraulic_condition', models.TextField(blank=True, null=True)),
                ('hydraulic_notes', models.TextField(blank=True, null=True)),
                ('hoses_condition', models.TextField(blank=True, null=True)),
                ('hoses_notes', models.TextField(blank=True, null=True)),
                ('reservoir_condition', models.TextField(blank=True, null=True)),
                ('reservoir_notes', models.TextField(blank=True, null=True)),
                ('seals_condition', models.TextField(blank=True, null=True)),
                ('seals_notes', models.TextField(blank=True, null=True)),
                ('filter_condition', models.TextField(blank=True, null=True)),
                ('filter_notes', models.TextField(blank=True, null=True)),
                ('cuts_condition', models.TextField(blank=True, null=True)),
                ('cuts_notes', models.TextField(blank=True, null=True)),
                ('light_condition', models.TextField(blank=True, null=True)),
                ('light_notes', models.TextField(blank=True, null=True)),
                ('tracks_condition', models.TextField(blank=True, null=True)),
                ('tracks_notes', models.TextField(blank=True, null=True)),
                ('fasteners_condition', models.TextField(blank=True, null=True)),
                ('fasteners_notes', models.TextField(blank=True, null=True)),
                ('pins_condition', models.TextField(blank=True, null=True)),
                ('pins_notes', models.TextField(blank=True, null=True)),
                ('guards_condition', models.TextField(blank=True, null=True)),
                ('guards_notes', models.TextField(blank=True, null=True)),
                ('braking_condition', models.TextField(blank=True, null=True)),
                ('braking_notes', models.TextField(blank=True, null=True)),
                ('emergency_condition', models.TextField(blank=True, null=True)),
                ('emergency_notes', models.TextField(blank=True, null=True)),
                ('steering_condition', models.TextField(blank=True, null=True)),
                ('steering_notes', models.TextField(blank=True, null=True)),
                ('crawler_condition', models.TextField(blank=True, null=True)),
                ('crawler_notes', models.TextField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections')),
            ],
            options={
                'db_table': 'insp_DailyMaintenance',
            },
        ),
    ]
