# Generated by Django 3.1 on 2020-10-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0023_dailymaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthmovingEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plants_name', models.CharField(blank=True, max_length=50)),
                ('equipment_name', models.CharField(blank=True, max_length=50)),
                ('equipment', models.CharField(blank=True, max_length=50)),
                ('other_specify', models.CharField(blank=True, max_length=50)),
                ('equipment_id', models.CharField(blank=True, max_length=50)),
                ('access_good', models.CharField(blank=True, max_length=50)),
                ('access_rejected', models.CharField(blank=True, max_length=50)),
                ('access_na', models.CharField(blank=True, max_length=50)),
                ('access_remarks', models.CharField(blank=True, max_length=50)),
                ('backup_good', models.CharField(blank=True, max_length=50)),
                ('engine_condition', models.CharField(blank=True, max_length=50)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections')),
            ],
            options={
                'db_table': 'insp_EarthmovingEquipment',
            },
        ),
    ]
