# Generated by Django 3.1 on 2020-10-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0026_emergencyrescue_energizedelectrical_equipmentdeficiency_equipmentinspection_equipmentoperator_eyewas'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyOxygen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plants_name', models.CharField(blank=True, max_length=50)),
                ('check_regulator', models.CharField(blank=True, max_length=15)),
                ('check_screens', models.CharField(blank=True, max_length=15)),
                ('check_pressure', models.CharField(blank=True, max_length=15)),
                ('check_leaking', models.CharField(blank=True, max_length=15)),
                ('check_cylinder', models.CharField(blank=True, max_length=15)),
                ('check_hose', models.CharField(blank=True, max_length=15)),
                ('check_hoses', models.CharField(blank=True, max_length=15)),
                ('check_inspect', models.CharField(blank=True, max_length=15)),
                ('check_arrester', models.CharField(blank=True, max_length=15)),
                ('check_rings', models.CharField(blank=True, max_length=15)),
                ('check_chamber', models.CharField(blank=True, max_length=15)),
                ('check_head', models.CharField(blank=True, max_length=15)),
                ('check_instructions', models.CharField(blank=True, max_length=15)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('person', models.CharField(blank=True, max_length=50)),
                ('target', models.CharField(blank=True, max_length=50)),
                ('action_two', models.CharField(blank=True, max_length=50)),
                ('person_two', models.CharField(blank=True, max_length=50)),
                ('target_two', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('unit_id', models.CharField(blank=True, max_length=50)),
                ('insp_name', models.CharField(blank=True, max_length=50)),
                ('sign', models.CharField(blank=True, max_length=50)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspections')),
            ],
            options={
                'db_table': 'insp_QuarterlyOxygen',
            },
        ),
    ]
