# Generated by Django 3.1 on 2020-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0028_safetystatistics_scaffoldinspection_shopoffice_skidsteer_spotinspection_subcontractoracknowledgment_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthmovingequipment',
            name='engine_condition',
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='backup_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='backup_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='backup_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='belts_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='belts_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='belts_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='belts_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='boom_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='boom_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='boom_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='boom_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='brakes_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='brakes_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='brakes_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='brakes_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='bulk_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='bulk_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='bulk_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='bulk_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='clutch_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='clutch_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='clutch_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='clutch_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cotter_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cotter_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cotter_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cotter_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cover_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cover_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cover_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='cover_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='decking_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='decking_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='decking_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='excess_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='excess_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='excess_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='excess_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='exhaust_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='exhaust_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='exhaust_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='exhaust_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fire_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fire_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fire_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fire_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='frames_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='frames_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='frames_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fuel_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fuel_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fuel_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='fuel_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='glass_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='glass_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='glass_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='glass_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='guards_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='guards_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='guards_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='guards_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='horn_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='horn_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='horn_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='horn_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='hydraulic_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='hydraulic_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='hydraulic_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='hydraulic_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='inspected_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lights_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lights_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lights_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lights_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lungs_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lungs_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lungs_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='lungs_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='muffler_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='muffler_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='muffler_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='muffler_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='operator_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='operator_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='operator_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='operator_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='outriggers_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='outriggers_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='outriggers_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='outriggers_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='parking_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='parking_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='parking_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='parking_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='positive_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='positive_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='positive_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='positive_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rear_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rear_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rear_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rear_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rollover_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rollover_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rollover_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='rollover_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steering_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steering_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steering_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steering_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steps_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steps_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steps_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='steps_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='tires_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='tires_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='tires_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='tires_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='windshield_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='windshield_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='windshield_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='windshield_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='access_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='access_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='access_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='access_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='backup_good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='equipment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='equipment_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='other_specify',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthmovingequipment',
            name='plants_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
