# Generated by Django 3.1 on 2020-10-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0031_auto_20201013_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsite',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
