# Generated by Django 3.1 on 2020-10-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0032_formalsite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentinvestigationrcaform',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
