# Generated by Django 3.1 on 2020-10-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0033_accidentinvestigationrcaform_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeacknowledgment',
            old_name='area',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='employeeacknowledgment',
            old_name='date_develop',
            new_name='emp_sign',
        ),
        migrations.RenameField(
            model_name='employeeacknowledgment',
            old_name='des_location',
            new_name='management_sign',
        ),
        migrations.RenameField(
            model_name='employeeacknowledgment',
            old_name='developed_by',
            new_name='manager_name',
        ),
        migrations.RemoveField(
            model_name='employeeacknowledgment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='employeeacknowledgment',
            name='permit',
        ),
        migrations.AddField(
            model_name='confinedspaceauthorization',
            name='cont_monitoring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='decking_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthmovingequipment',
            name='frames_na',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastest',
            name='des_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
