# Generated by Django 3.1 on 2020-10-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0034_auto_20201019_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='portableladder',
            name='checklist_extended',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='genericsafe',
            name='gas_test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
