# Generated by Django 3.1 on 2020-10-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0036_subcontractoracknowledgment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontractororientation',
            old_name='_done',
            new_name='other_done',
        ),
        migrations.RenameField(
            model_name='subcontractororientation',
            old_name='_na',
            new_name='other_na',
        ),
    ]
